-- gresit
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
BEGIN TRANSACTION;
SELECT * FROM Orase
WAITFOR DELAY '00:00:07';
SELECT * FROM Orase
COMMIT TRAN;

-- corect
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
BEGIN TRANSACTION
SELECT * FROM Orase
WAITFOR DELAY '00:00:07'
SELECT * FROM Orase
COMMIT TRANSACTION