-- gresit
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
BEGIN TRANSACTION;
SELECT * FROM Produse
WAITFOR DELAY '00:00:07';
SELECT * FROM Produse
COMMIT TRAN;

-- corect
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
BEGIN TRANSACTION
SELECT * FROM Produse
WAITFOR DELAY '00:00:07'
SELECT * FROM Produse
COMMIT TRANSACTION
INSERT INTO LogTable(actiune, data, mesaj) VALUES('Phantom reads', CURRENT_TIMESTAMP, 'PR succeded')
