-- gresit
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
BEGIN TRAN
SELECT * FROM Briose;
WAITFOR DELAY '00:00:10'
SELECT * FROM Briose;
COMMIT TRAN

-- corect
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
BEGIN TRAN
SELECT * FROM Briose;
WAITFOR DELAY '00:00:10'
SELECT * FROM Briose;
COMMIT TRAN
