######################################################################
# Automatically generated by qmake (3.1) Fri Jun 9 08:42:13 2023
######################################################################

TEMPLATE = app
TARGET = "Agentie de turism"
INCLUDEPATH += .
QT += core gui widgets
# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
HEADERS += Cos_GUI.h \
           Cos_Oferte.h \
           HistrogramGUI.h \
           observer.h \
           oferta.h \
           OfertaStoreGUI.h \
           Repo.h \
           Service.h \
           StoreGUIModele.h \
           TableModel.h \
           Teste.h \
           Undo.h \
           Validator.h
SOURCES += Cos_Oferte.cpp \
           main.cpp \
           oferta.cpp \
           OfertaStoreGUI.cpp \
           Repo.cpp \
           Service.cpp \
           StoreGUIModele.cpp \
           Teste.cpp \
           Validator.cpp
