######################################################################
# Automatically generated by qmake (3.1) Mon May 15 15:29:17 2023
######################################################################

TEMPLATE = app
TARGET = "Agentie de turism"
INCLUDEPATH += .

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
HEADERS += AgentieService.h \
           consola.h \
           CosOferte.h \
           Errors.h \
           Oferta.h \
           OfertaRepo.h \
           OfertaStoreGUI.h \
           teste.h \
           Undo.h \
           Validator.h
SOURCES += AgentieService.cpp \
           consola.cpp \
           CosOferte.cpp \
           main.cpp \
           Oferta.cpp \
           OfertaRepo.cpp \
           OfertaStoreGUI.cpp \
           RepoLab.cpp \
           teste.cpp \
           Validator.cpp
           
QT += core gui widgets
