-- corect
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
BEGIN TRANSACTION
SELECT * FROM Melodii;
WAITFOR DELAY '00:00:06'
SELECT * FROM Melodii;
COMMIT TRANSACTION


-- gresit
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
BEGIN TRANSACTION
SELECT * FROM Melodii;
WAITFOR DELAY '00:00:06'
SELECT * FROM Melodii;
COMMIT TRANSACTION